#!/usr/bin/env bash
# This script installs fixes the Nginx configuration file to listen on port 80
sudo sed -i 's/8080/80/g'  /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
